---
# #########################################
# repo locations from repo root
team_images: "assets/static/media/team/"
team_images_url: "/static/media/team/"
default_image: "/static/media/team/gender_neutral_user.png"
data_bag: "databags/team.yaml"
# destination url
# #########################################
# MAP G-SHEET COLUMNS TO KEYS
# #########################################
member:
  # column name in G-Sheet: attribute in data model
  "BlueSky  (URL)": "bluesky"
  "Committee": "committee"
  "Mastodon  (URL)": "mastodon"
  "Git": "github"
  "Upload picture": "image_url"
  "LinkedIn  (URL)": "linkedin"
  "Name": "name"
  "Homepage  (URL)": "website"
  "Would you like to appear on Meet the Team page?": "ignore"
  "X/Twitter (URL)": "twitter"
  "Committee Chair": "chair"
# #########################################
# sort order for list on website, unlisted keys will at the end
sort_order:
  - 'Steering'
  - 'Pioneers Hub Office'
  - 'Program'
  - 'Diversity'
  - 'On-Site'
  - 'Expericence'
  - 'Video'
  - 'Code of Conduct'
  - 'PyLadies'
  - 'Sprints'
  - 'other'
# #########################################
# destination github repo
git_repo_url: "https://github.com/PioneersHub/pyconde-website"
# path to work directory for git repo from project root
local_repo_path: "repo"
# branch to make changes in
branch_name: "auto-update-team-page"
pr_base_branch: "main"
repo_owner: "PioneersHub"
repo_name: "pyconde-website"
pr_reviewers:
  - "alanderex"
# #########################################
